### PR TITLE
text: make CacheGlyphs create all the sub-pixel variations

### PR DESCRIPTION
**Pull request by hajimehoshi**
Before this change, CacheGlyphs created only necessary glyphs wihtout considering variations by sub-pixels in X direction. This was sometimes unexpected when a user might want to prepare glyph cache with a string including all the letters, instead of actual texts.

This change makes CacheGlyphs create all the sub-pixel variations of the given runes.

Updates #2469
Updates #2528

### CODE REVIEW

**Comment by hajimehoshi** [comment]
@divVerent Please take a look.

**Comment by divVerent** [comment]
This looks like it will work. Let me quickly test - with my other PR (texture unit bug) still open this is really easy to verify :)

**Comment by hajimehoshi** [comment]
> with my other PR (texture unit bug) still open this is really easy to verify :)

I'll merge your PR as soon as possible after all the tests pass.

**Comment by divVerent** [comment]
Yes, confirmed the glyph cache is complete with this - with this commit, my game also works fine despite the texture unit bug.

That bug was a nice test case for the glyph cache working, as the precaching happened at frame start where no shader calls took place yet :)

**Pull request merged**
