### PR TITLE
Fallback to simpler logic when trying to get DPI from monitor and failing

### PR DESCRIPTION
**Pull request by corfe83**
This fixes a crash on at least one of my customer's machines. I don't have access to the machine, so I don't know why it's failing.

Instead of crashing, just falls back to other DPI.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Thanks!

1. Could you file the bug first for the recording?
2. Could you add a comment about this bug with the filed issue?

**Comment by hajimehoshi** [comment]
The comment will be like:

`// monitorFromRect can fail in some environments (#1601)`

**Comment by hajimehoshi** [comment]
friendly ping

**Comment by corfe83** [comment]
Thanks for feedback, I've filed a bug and added the comments.

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
