### PR TITLE
Fix typos, and use panic instead of log.Fatal in doc.go

### PR DESCRIPTION
**Pull request by fuyuaki**
The use of panic is to match the image.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Thank you for fixing the typos, but why do you prefer `panic` to `log.Fatal`?

If we want to replace it, let's create a separate PR for that.

**Comment by hajimehoshi** [comment]
If I don't get your answer until tomorrow, I'll pick the typo fixes from your PR instead of merging it. Thanks.

**Comment by fuyuaki** [comment]
I thought it would be good the code would match the overview image. Not about preference. I overthought about it.

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
