### PR TITLE
ebitenutil/file: Fix OpenFile() so it works with wasm

### PR DESCRIPTION
**Pull request by silbinarywolf**
* Change to use `js.NewCallback`
* Use `uint8contentWrapper := js.Global().Get("Uint8Array").New(content)`, without this all the bytes in `data` stays zeroed. (TypedArray cannot use `set` on an ArrayBuffer)

### CODE REVIEW

**Comment by hajimehoshi** [comment]
This change leaks callback objects. The callback objects should be one, or be deleted correctly.

**Comment by silbinarywolf** [comment]
@hajimehoshi I didnt understand what you meant initially, but I just CTRL+F'd through the Golang source code for `js.NewCallback` to see how they used it.

Is this fine?

**Comment by hajimehoshi** [comment]
I'm not sure what code you are pointing out, but in this PR's case, `NewCallback` is called whenever `OpenFile` is called, right?

**Comment by hajimehoshi** [comment]
Ah sorry I missed them

**Comment by hajimehoshi** [comment]
Updated .travis.yml to use the latest Go (and GopherJS). Could you rebase this PR and let TravisCI run again? Thanks!

**Pull request merged**
