### PR TITLE
all: fix typos

### PR DESCRIPTION
**Pull request by pierrec**
Signed-off-by: Pierre Curto <pierre.curto@gmail.com>

# What issue is this addressing?

### CODE REVIEW

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Review by hajimehoshi — CHANGES_REQUESTED** [review]
Please check the test results.

https://github.com/hajimehoshi/ebiten/actions/runs/4031142660/jobs/6930260852#step:6:34

**Comment by pierrec** [comment]
Yes sorry, my IDE messed up. Resending a PR.

Le sam. 28 janv. 2023 à 10:25, Hajime Hoshi ***@***.***> a
écrit :

**Comment by hajimehoshi** [comment]
What's the difference between this and #2559?

**Comment by pierrec** [comment]
Same. I may have broken things since I amended the previous commit.

**Review by hajimehoshi — APPROVED** [review]

**Pull request merged**
