### PR TITLE
Reimplement DrawLine using DrawTriangles

### PR DESCRIPTION
**Pull request by jstaf**
This provides a DrawLine implementation that doesn't run into the performance issues from #1655 (because it doesn't use ColorM), and adds an extra utility function to draw a line with variable width. Though it looks a little dodgy if you draw a wide line exactly horizontally or vertically (it draws a parallelogram instead of a rectangle), it looks quite nice when used to draw paths and gradients. I think the only example that uses DrawLine is the raycasting one and you can't tell the difference too much unless you look really closely, so I attached a screenshot that demos the new line drawing from one of my projects. 

Screenshot from 2021-05-29 20-05-44

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Hmm, I fine to reimplement `DrawLine` with `DrawTriangles`, but I didn't want `DrawLineWidth` since functions `DrawLine` and `DrawRect` in `ebitendebug` are just for debugging, and I didn't intend these functions for production usages.

**Comment by jstaf** [comment]
> but I didn't want DrawLineWidth since functions DrawLine and DrawRect in ebitendebug are just for debugging, and I didn't intend these functions for production usages.

Out of curiosity, why not? You say these functions aren't for production use, but there is no other way to draw a line with Ebiten. This is pretty important functionality for a game engine. For instance, Pixel has https://github.com/faiface/pixel/wiki/Drawing-shapes-with-IMDraw and LibGDX has https://github.com/libgdx/libgdx/wiki/Rendering-shapes

**Comment by hajimehoshi** [comment]
> there is no other way to draw a line with Ebiten.
So I plan to polish the current vector package but now I'm pretty busy with other tasks.

> This is pretty important functionality for a game engine.
IMO rendering lines is less essential than the other features like rendering images, and actually there are some Ebiten games in production without using this feature. I understand, however, many people including you want to render vector graphics for various purposes rather than developing just a simple game.

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen if you would like to update this. Thanks.

**Pull request closed without merging**
