### PR TITLE
js: Detecting pulse input on browser

### PR DESCRIPTION
**Pull request by 1l0**
This is not intended to merge. Just showing how I tried to detect pulse input on browsers.
Tap works but there is a glitch for drag arised from this.
Sorry for commit messages.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
> Sorry for commit messages.

No problem: all commits will be squashed so please make commits as you like :-)

**Comment by hajimehoshi** [comment]
> Just showing how I tried to detect pulse input on browsers.
> Tap works but there is a glitch for drag arised from this.

I don't understand the intention of this PR yet.  Why can this detect pulse input?

**Comment by 1l0** [comment]
Check the difference of behaviour of examples/paint on a browser with tap on macOS trackpad.

**Comment by hajimehoshi** [comment]
Tried but I couldn't notice the difference...

**Comment by hajimehoshi** [comment]
@1l0 Could you tell me how different they are?

**Comment by 1l0** [comment]
On [official example](https://hajimehoshi.github.io/ebiten/examples/paint.html), single tap doesn't work sometimes for me.

**Comment by hajimehoshi** [comment]
* Do you use a Magic Trackpad? I'm using a trackpad on a MacBook Pro, and I don't think there is a difference between them.
* Perhaps, did you enable 'tap to click'? I didn't, and I'll enable it and try again later. http://osxdaily.com/2014/01/28/enable-tap-to-click-mac-trackpad/

**Comment by 1l0** [comment]
Tap to click is enabled using MacBook trackpad.

**Comment by hajimehoshi** [comment]
Confirmed that your PR changed the situation.

* In both cases, taps were ignored in most cases.
* It looks like more taps could be recognized with your PR than the original state.
* Strokes didn't end until the next tap with your PR

**Comment by hajimehoshi** [comment]
I understand a tap is treated as a click, but should this be treated as mousedown/up or drag events? I'm a little confused.

**Comment by 1l0** [comment]
That's strange, taps are not ignored on this PR for me. Anyway yes this PR is not a sort of solution to fix something but my demand was just simply to detect a tap on my environment so perhaps you don't need to bother with it at all.

**Pull request closed without merging**
