### PR TITLE
examples/font: simplify code

### PR DESCRIPTION
**Pull request by martinlindhe**

### CODE REVIEW

**Comment by martinlindhe** [comment]
on second look, not sure this is correct.
it no longer can use ebitenutil\file_js.go OpenFile(), so i guess it breaks in browsers?

**Comment by hajimehoshi** [comment]
I guess `ioutil.ReadFile` works only with node, but not sure. `ebiten.OpenFile` uses XHR so that it works on browsers. Have you checked that?

**Comment by martinlindhe** [comment]
i have not checked with browsers, can do that, but i'' having doubts if this was a valid fix in the first place :-) might just drop it

**Comment by hajimehoshi** [comment]
Sure, let me close this once. Please feel free to reopen this if you confirm this is a problem.

**Pull request closed without merging**
