### PR TITLE
update purego

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
update to commit [cce0ae8](https://github.com/ebitengine/purego/commit/cce0ae8e7ec8f56ec142abf1fff514dbc7a2fd54)

### CODE REVIEW

**Comment by hajimehoshi** [comment]
What is the point of this fix? Thanks!

**Comment by hajimehoshi** [comment]
Unfortunately, I cannot merge this unless https://github.com/ebitengine/purego/pull/6#issuecomment-1153479355 is solved.

**Comment by TotallyGamerJet** [comment]
Whoops! Didn't see that. I'll take a look. Thanks!

**Comment by hajimehoshi** [comment]
Confirmed the latest purego worked well with Ebitengine. Are you sending a PR, or shall I update go.mod?

**Comment by TotallyGamerJet** [comment]
@hajimehoshi you can go ahead and do it. If you don’t I’ll probably merge the windows and Darwin version of OpenGL

**Comment by hajimehoshi** [comment]
I'll update go.mod. I'll delegate the rest part to you. Thanks!

**Pull request closed without merging**
