### PR TITLE
internal/ui: Use new OBJC API

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
# What issue is this addressing?

updates #1162 

## What this PR does | solves

Use the new ObjC API inside of purego.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Thanks.

By the way, updating Oto would be precedent to Ebitengine.

**Comment by hajimehoshi** [comment]
Is this PR ready for review?

**Comment by TotallyGamerJet** [comment]
Yea

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

I also confirmed all the tests passed on my MacBook Pro.

**Pull request merged**
